local _yc = 0

local function set(inst, prop, value)
    local ok = pcall(function() inst[prop] = value end)
    if not ok and sethiddenproperty then
        pcall(sethiddenproperty, inst, prop, value)
    end
    _yc = _yc + 1
    if _yc % 150 == 0 then task.wait() end
end

local function setParent(inst, parent)
    pcall(function() inst.Parent = parent end)
end

local function setAttr(inst, name, value)
    pcall(function() inst:SetAttribute(name, value) end)
end

local objects = {}
objects[1] = Instance.new("ScreenGui")
objects[2] = Instance.new("Frame")
objects[3] = Instance.new("Frame")
objects[4] = Instance.new("ImageLabel")
objects[5] = Instance.new("ImageLabel")
objects[6] = Instance.new("UIGradient")
objects[7] = Instance.new("ImageLabel")
objects[8] = Instance.new("TextLabel")
objects[9] = Instance.new("TextLabel")
objects[10] = Instance.new("TextLabel")
objects[11] = Instance.new("TextLabel")
objects[12] = Instance.new("ImageLabel")
objects[13] = Instance.new("ImageButton")
objects[14] = Instance.new("UIScale")

set(objects[1], "Name", "Bar")
set(objects[1], "ActiveQueryNames", "")
set(objects[1], "Attributes", "")
set(objects[1], "AttributesReplicate", "")
set(objects[1], "AttributesSerialize", "")
set(objects[1], "AutoLocalize", true)
set(objects[1], "ClipToDeviceSafeArea", true)
set(objects[1], "ClippedRect", Rect.new(-math.huge, -math.huge, math.huge, math.huge))
set(objects[1], "DefinesCapabilities", false)
set(objects[1], "DisplayOrder", 0)
set(objects[1], "Enabled", true)
set(objects[1], "IgnoreGuiInset", false)
set(objects[1], "IsNotOccluded", true)
set(objects[1], "Localize", true)
set(objects[1], "OnTopOfCoreBlur", false)
set(objects[1], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[1], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[1], "RawRect2D", Rect.new(0, 58, 1180, 820))
set(objects[1], "ReplicatedInsertionOrder", 2147483647)
set(objects[1], "ResetOnSpawn", true)
set(objects[1], "SafeAreaCompatibility", Enum.SafeAreaCompatibility.FullscreenExtension)
set(objects[1], "Sandboxed", false)
set(objects[1], "ScreenInsets", Enum.ScreenInsets.CoreUISafeInsets)
set(objects[1], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[1], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[1], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[1], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[1], "SelectionGroup", false)
set(objects[1], "SourceAssetId", -1)
set(objects[1], "Tags", "")
set(objects[1], "TotalGroupScale", 1)
set(objects[1], "ZIndexBehavior", Enum.ZIndexBehavior.Global)
set(objects[1], "archivable", true)
set(objects[1], "className", "ScreenGui")
set(objects[1], "numExpectedDirectChildren", 0)

set(objects[2], "Name", "MagicHealth")
set(objects[2], "Size", UDim2.fromOffset(397, 25))
set(objects[2], "Position", UDim2.new(0.5, 0, 1, -90))
set(objects[2], "AnchorPoint", Vector2.new(0.5, 0.5))
set(objects[2], "Visible", false)
set(objects[2], "ZIndex", 1)
set(objects[2], "Active", false)
set(objects[2], "ActiveQueryNames", "")
set(objects[2], "Attributes", "")
set(objects[2], "AttributesReplicate", "")
set(objects[2], "AttributesSerialize", "")
set(objects[2], "AutoLocalize", true)
set(objects[2], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[2], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[2], "BorderColor", BrickColor.new("Black"))
set(objects[2], "ClippedRect", Rect.new(-math.huge, -math.huge, math.huge, math.huge))
set(objects[2], "ClipsDescendants", false)
set(objects[2], "DefinesCapabilities", false)
set(objects[2], "DragBeginConnectionCount", 0)
set(objects[2], "DragStoppedConnectionCount", 0)
set(objects[2], "Draggable", false)
set(objects[2], "GuiState", Enum.GuiState.Idle)
set(objects[2], "InputSink", Enum.InputSink.None)
set(objects[2], "Interactable", true)
set(objects[2], "IsNotOccluded", true)
set(objects[2], "LayoutOrder", 0)
set(objects[2], "Localize", true)
set(objects[2], "MouseEnterConnectionCount", 0)
set(objects[2], "MouseLeaveConnectionCount", 0)
set(objects[2], "MouseMovedConnectionCount", 0)
set(objects[2], "MouseWheelBackwardConnectionCount", 0)
set(objects[2], "MouseWheelForwardConnectionCount", 0)
set(objects[2], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[2], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[2], "RawRect2D", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[2], "ReplicatedInsertionOrder", 432)
set(objects[2], "Rotation", 0)
set(objects[2], "Sandboxed", false)
set(objects[2], "Selectable", false)
set(objects[2], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[2], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[2], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[2], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[2], "SelectionGroup", false)
set(objects[2], "SelectionOrder", 0)
set(objects[2], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[2], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[2], "SourceAssetId", -1)
set(objects[2], "Style", Enum.FrameStyle.Custom)
set(objects[2], "Tags", "")
set(objects[2], "TotalGroupScale", 1)
set(objects[2], "Transparency", 1)
set(objects[2], "archivable", true)
set(objects[2], "className", "Frame")
set(objects[2], "numExpectedDirectChildren", 0)

set(objects[3], "Name", "Health")
set(objects[3], "Size", UDim2.fromScale(1, 1))
set(objects[3], "Position", UDim2.new())
set(objects[3], "AnchorPoint", Vector2.new())
set(objects[3], "Visible", true)
set(objects[3], "ZIndex", 1)
set(objects[3], "Active", false)
set(objects[3], "ActiveQueryNames", "")
set(objects[3], "Attributes", "")
set(objects[3], "AttributesReplicate", "")
set(objects[3], "AttributesSerialize", "")
set(objects[3], "AutoLocalize", true)
set(objects[3], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[3], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[3], "BorderColor", BrickColor.new("Black"))
set(objects[3], "ClippedRect", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[3], "ClipsDescendants", true)
set(objects[3], "DefinesCapabilities", false)
set(objects[3], "DragBeginConnectionCount", 0)
set(objects[3], "DragStoppedConnectionCount", 0)
set(objects[3], "Draggable", false)
set(objects[3], "GuiState", Enum.GuiState.Idle)
set(objects[3], "InputSink", Enum.InputSink.None)
set(objects[3], "Interactable", true)
set(objects[3], "IsNotOccluded", true)
set(objects[3], "LayoutOrder", 0)
set(objects[3], "Localize", true)
set(objects[3], "MouseEnterConnectionCount", 0)
set(objects[3], "MouseLeaveConnectionCount", 0)
set(objects[3], "MouseMovedConnectionCount", 0)
set(objects[3], "MouseWheelBackwardConnectionCount", 0)
set(objects[3], "MouseWheelForwardConnectionCount", 0)
set(objects[3], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[3], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[3], "RawRect2D", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[3], "ReplicatedInsertionOrder", 425)
set(objects[3], "Rotation", 0)
set(objects[3], "Sandboxed", false)
set(objects[3], "Selectable", false)
set(objects[3], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[3], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[3], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[3], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[3], "SelectionGroup", false)
set(objects[3], "SelectionOrder", 0)
set(objects[3], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[3], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[3], "SourceAssetId", -1)
set(objects[3], "Style", Enum.FrameStyle.Custom)
set(objects[3], "Tags", "")
set(objects[3], "TotalGroupScale", 1)
set(objects[3], "Transparency", 1)
set(objects[3], "archivable", true)
set(objects[3], "className", "Frame")
set(objects[3], "numExpectedDirectChildren", 0)

set(objects[4], "Name", "Bar")
set(objects[4], "Size", UDim2.new(1, 0, 0, 25))
set(objects[4], "Position", UDim2.new(0, 0, 1, -25))
set(objects[4], "AnchorPoint", Vector2.new())
set(objects[4], "Visible", true)
set(objects[4], "ZIndex", 3)
set(objects[4], "Active", false)
set(objects[4], "ActiveQueryNames", "")
set(objects[4], "Attributes", "")
set(objects[4], "AttributesReplicate", "")
set(objects[4], "AttributesSerialize", "")
set(objects[4], "AutoLocalize", true)
set(objects[4], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[4], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[4], "BorderColor", BrickColor.new("Black"))
set(objects[4], "ClippedRect", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[4], "ClipsDescendants", true)
set(objects[4], "ContentImageSize", Vector2.new())
set(objects[4], "DefinesCapabilities", false)
set(objects[4], "DragBeginConnectionCount", 0)
set(objects[4], "DragStoppedConnectionCount", 0)
set(objects[4], "Draggable", false)
set(objects[4], "GuiState", Enum.GuiState.Idle)
set(objects[4], "ImageRectOffset", Vector2.new())
set(objects[4], "ImageRectSize", Vector2.new())
set(objects[4], "InputSink", Enum.InputSink.None)
set(objects[4], "Interactable", true)
set(objects[4], "IsNotOccluded", true)
set(objects[4], "LayoutOrder", 0)
set(objects[4], "Localize", true)
set(objects[4], "MouseEnterConnectionCount", 0)
set(objects[4], "MouseLeaveConnectionCount", 0)
set(objects[4], "MouseMovedConnectionCount", 0)
set(objects[4], "MouseWheelBackwardConnectionCount", 0)
set(objects[4], "MouseWheelForwardConnectionCount", 0)
set(objects[4], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[4], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[4], "RawRect2D", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[4], "ReplicatedInsertionOrder", 423)
set(objects[4], "ResampleMode", Enum.ResamplerMode.Default)
set(objects[4], "Rotation", 0)
set(objects[4], "Sandboxed", false)
set(objects[4], "Selectable", false)
set(objects[4], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[4], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[4], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[4], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[4], "SelectionGroup", false)
set(objects[4], "SelectionOrder", 0)
set(objects[4], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[4], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[4], "SourceAssetId", -1)
set(objects[4], "Tags", "")
set(objects[4], "TotalGroupScale", 1)
set(objects[4], "Transparency", 1)
set(objects[4], "archivable", true)
set(objects[4], "className", "ImageLabel")
set(objects[4], "numExpectedDirectChildren", 0)

set(objects[5], "Name", "Bar")
set(objects[5], "Size", UDim2.fromOffset(397, 25))
set(objects[5], "Position", UDim2.new(0, 0, 1, -25))
set(objects[5], "AnchorPoint", Vector2.new())
set(objects[5], "Visible", true)
set(objects[5], "ZIndex", 3)
set(objects[5], "Active", false)
set(objects[5], "ActiveQueryNames", "")
set(objects[5], "Attributes", "")
set(objects[5], "AttributesReplicate", "")
set(objects[5], "AttributesSerialize", "")
set(objects[5], "AutoLocalize", true)
set(objects[5], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[5], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[5], "BorderColor", BrickColor.new("Black"))
set(objects[5], "ClippedRect", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[5], "ClipsDescendants", false)
set(objects[5], "ContentImageSize", Vector2.new())
set(objects[5], "DefinesCapabilities", false)
set(objects[5], "DragBeginConnectionCount", 0)
set(objects[5], "DragStoppedConnectionCount", 0)
set(objects[5], "Draggable", false)
set(objects[5], "GuiState", Enum.GuiState.Idle)
set(objects[5], "ImageRectOffset", Vector2.new())
set(objects[5], "ImageRectSize", Vector2.new())
set(objects[5], "InputSink", Enum.InputSink.None)
set(objects[5], "Interactable", true)
set(objects[5], "IsNotOccluded", true)
set(objects[5], "LayoutOrder", 0)
set(objects[5], "Localize", true)
set(objects[5], "MouseEnterConnectionCount", 0)
set(objects[5], "MouseLeaveConnectionCount", 0)
set(objects[5], "MouseMovedConnectionCount", 0)
set(objects[5], "MouseWheelBackwardConnectionCount", 0)
set(objects[5], "MouseWheelForwardConnectionCount", 0)
set(objects[5], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[5], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[5], "RawRect2D", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[5], "ReplicatedInsertionOrder", 422)
set(objects[5], "ResampleMode", Enum.ResamplerMode.Default)
set(objects[5], "Rotation", 0)
set(objects[5], "Sandboxed", false)
set(objects[5], "Selectable", false)
set(objects[5], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[5], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[5], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[5], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[5], "SelectionGroup", false)
set(objects[5], "SelectionOrder", 0)
set(objects[5], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[5], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[5], "SourceAssetId", -1)
set(objects[5], "Tags", "")
set(objects[5], "TotalGroupScale", 1)
set(objects[5], "Transparency", 1)
set(objects[5], "archivable", true)
set(objects[5], "className", "ImageLabel")
set(objects[5], "numExpectedDirectChildren", 0)

set(objects[6], "Name", "Empty")
set(objects[6], "Attributes", "")
set(objects[6], "AttributesReplicate", "")
set(objects[6], "AttributesSerialize", "")
set(objects[6], "DefinesCapabilities", false)
set(objects[6], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[6], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[6], "Sandboxed", false)
set(objects[6], "SourceAssetId", -1)
set(objects[6], "Tags", "")
set(objects[6], "archivable", true)
set(objects[6], "className", "UIGradient")
set(objects[6], "numExpectedDirectChildren", 0)

set(objects[7], "Name", "Glow")
set(objects[7], "Size", UDim2.fromOffset(397, 25))
set(objects[7], "Position", UDim2.new())
set(objects[7], "AnchorPoint", Vector2.new())
set(objects[7], "Visible", true)
set(objects[7], "ZIndex", 7)
set(objects[7], "Active", false)
set(objects[7], "ActiveQueryNames", "")
set(objects[7], "Attributes", "")
set(objects[7], "AttributesReplicate", "")
set(objects[7], "AttributesSerialize", "")
set(objects[7], "AutoLocalize", true)
set(objects[7], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[7], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[7], "BorderColor", BrickColor.new("Black"))
set(objects[7], "ClippedRect", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[7], "ClipsDescendants", false)
set(objects[7], "ContentImageSize", Vector2.new())
set(objects[7], "DefinesCapabilities", false)
set(objects[7], "DragBeginConnectionCount", 0)
set(objects[7], "DragStoppedConnectionCount", 0)
set(objects[7], "Draggable", false)
set(objects[7], "GuiState", Enum.GuiState.Idle)
set(objects[7], "ImageRectOffset", Vector2.new())
set(objects[7], "ImageRectSize", Vector2.new())
set(objects[7], "InputSink", Enum.InputSink.None)
set(objects[7], "Interactable", true)
set(objects[7], "IsNotOccluded", true)
set(objects[7], "LayoutOrder", 0)
set(objects[7], "Localize", true)
set(objects[7], "MouseEnterConnectionCount", 0)
set(objects[7], "MouseLeaveConnectionCount", 0)
set(objects[7], "MouseMovedConnectionCount", 0)
set(objects[7], "MouseWheelBackwardConnectionCount", 0)
set(objects[7], "MouseWheelForwardConnectionCount", 0)
set(objects[7], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[7], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[7], "RawRect2D", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[7], "ReplicatedInsertionOrder", 424)
set(objects[7], "ResampleMode", Enum.ResamplerMode.Default)
set(objects[7], "Rotation", 0)
set(objects[7], "Sandboxed", false)
set(objects[7], "Selectable", false)
set(objects[7], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[7], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[7], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[7], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[7], "SelectionGroup", false)
set(objects[7], "SelectionOrder", 0)
set(objects[7], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[7], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[7], "SourceAssetId", -1)
set(objects[7], "Tags", "")
set(objects[7], "TotalGroupScale", 1)
set(objects[7], "Transparency", 1)
set(objects[7], "archivable", true)
set(objects[7], "className", "ImageLabel")
set(objects[7], "numExpectedDirectChildren", 0)

set(objects[8], "Name", "TextLabel")
set(objects[8], "Size", UDim2.fromOffset(163, 25))
set(objects[8], "Position", UDim2.new(0.5, 0, -0.84000003, 10))
set(objects[8], "AnchorPoint", Vector2.new(0.5, 0))
set(objects[8], "Visible", true)
set(objects[8], "ZIndex", 8)
set(objects[8], "Active", false)
set(objects[8], "ActiveQueryNames", "")
set(objects[8], "Attributes", "")
set(objects[8], "AttributesReplicate", "")
set(objects[8], "AttributesSerialize", "")
set(objects[8], "AutoLocalize", true)
set(objects[8], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[8], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[8], "BorderColor", BrickColor.new("Black"))
set(objects[8], "ClippedRect", Rect.new(-math.huge, -math.huge, math.huge, math.huge))
set(objects[8], "ClipsDescendants", false)
set(objects[8], "Confidential", false)
set(objects[8], "DefinesCapabilities", false)
set(objects[8], "DragBeginConnectionCount", 0)
set(objects[8], "DragStoppedConnectionCount", 0)
set(objects[8], "Draggable", false)
set(objects[8], "FontSize", Enum.FontSize.Size24)
set(objects[8], "GuiState", Enum.GuiState.Idle)
set(objects[8], "InputSink", Enum.InputSink.None)
set(objects[8], "Interactable", true)
set(objects[8], "IsNotOccluded", true)
set(objects[8], "LayoutOrder", 0)
set(objects[8], "LocalizationMatchIdentifier", "")
set(objects[8], "LocalizationMatchedSourceText", "")
set(objects[8], "Localize", true)
set(objects[8], "LocalizedText", "SERIOUS MODE")
set(objects[8], "MouseEnterConnectionCount", 0)
set(objects[8], "MouseLeaveConnectionCount", 0)
set(objects[8], "MouseMovedConnectionCount", 0)
set(objects[8], "MouseWheelBackwardConnectionCount", 0)
set(objects[8], "MouseWheelForwardConnectionCount", 0)
set(objects[8], "OpenTypeFeaturesError", "")
set(objects[8], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[8], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[8], "RawRect2D", Rect.new(508.5, 706.5, 671.5, 731.5))
set(objects[8], "ReplicatedInsertionOrder", 427)
set(objects[8], "Rotation", 0)
set(objects[8], "Sandboxed", false)
set(objects[8], "Selectable", false)
set(objects[8], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[8], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[8], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[8], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[8], "SelectionGroup", false)
set(objects[8], "SelectionOrder", 0)
set(objects[8], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[8], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[8], "SourceAssetId", -1)
set(objects[8], "Tags", "")
set(objects[8], "Text", "SERIOUS MODE")
set(objects[8], "TextColor", BrickColor.new("Institutional white"))
set(objects[8], "TextSize", 22)
set(objects[8], "TextWrap", false)
set(objects[8], "TextXAlignment", Enum.TextXAlignment.Center)
set(objects[8], "TextYAlignment", Enum.TextYAlignment.Center)
set(objects[8], "TotalGroupScale", 1)
set(objects[8], "Transparency", 1)
set(objects[8], "archivable", true)
set(objects[8], "className", "TextLabel")
set(objects[8], "numExpectedDirectChildren", 0)

set(objects[9], "Name", "TextLabel")
set(objects[9], "Size", UDim2.fromOffset(163, 25))
set(objects[9], "Position", UDim2.new(0.5, 2, 0, 2))
set(objects[9], "AnchorPoint", Vector2.new(0.5, 0))
set(objects[9], "Visible", true)
set(objects[9], "ZIndex", 3)
set(objects[9], "Active", false)
set(objects[9], "ActiveQueryNames", "")
set(objects[9], "Attributes", "")
set(objects[9], "AttributesReplicate", "")
set(objects[9], "AttributesSerialize", "")
set(objects[9], "AutoLocalize", true)
set(objects[9], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[9], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[9], "BorderColor", BrickColor.new("Black"))
set(objects[9], "ClippedRect", Rect.new(-math.huge, -math.huge, math.huge, math.huge))
set(objects[9], "ClipsDescendants", false)
set(objects[9], "Confidential", false)
set(objects[9], "DefinesCapabilities", false)
set(objects[9], "DragBeginConnectionCount", 0)
set(objects[9], "DragStoppedConnectionCount", 0)
set(objects[9], "Draggable", false)
set(objects[9], "FontSize", Enum.FontSize.Size24)
set(objects[9], "GuiState", Enum.GuiState.Idle)
set(objects[9], "InputSink", Enum.InputSink.None)
set(objects[9], "Interactable", true)
set(objects[9], "IsNotOccluded", true)
set(objects[9], "LayoutOrder", 0)
set(objects[9], "LocalizationMatchIdentifier", "")
set(objects[9], "LocalizationMatchedSourceText", "")
set(objects[9], "Localize", true)
set(objects[9], "LocalizedText", "SERIOUS MODE")
set(objects[9], "MouseEnterConnectionCount", 0)
set(objects[9], "MouseLeaveConnectionCount", 0)
set(objects[9], "MouseMovedConnectionCount", 0)
set(objects[9], "MouseWheelBackwardConnectionCount", 0)
set(objects[9], "MouseWheelForwardConnectionCount", 0)
set(objects[9], "OpenTypeFeaturesError", "")
set(objects[9], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[9], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[9], "RawRect2D", Rect.new(510.5, 708.5, 673.5, 733.5))
set(objects[9], "ReplicatedInsertionOrder", 426)
set(objects[9], "Rotation", 0)
set(objects[9], "Sandboxed", false)
set(objects[9], "Selectable", false)
set(objects[9], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[9], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[9], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[9], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[9], "SelectionGroup", false)
set(objects[9], "SelectionOrder", 0)
set(objects[9], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[9], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[9], "SourceAssetId", -1)
set(objects[9], "Tags", "")
set(objects[9], "Text", "SERIOUS MODE")
set(objects[9], "TextColor", BrickColor.new("Really black"))
set(objects[9], "TextSize", 22)
set(objects[9], "TextWrap", false)
set(objects[9], "TextXAlignment", Enum.TextXAlignment.Center)
set(objects[9], "TextYAlignment", Enum.TextYAlignment.Center)
set(objects[9], "TotalGroupScale", 1)
set(objects[9], "Transparency", 1)
set(objects[9], "archivable", true)
set(objects[9], "className", "TextLabel")
set(objects[9], "numExpectedDirectChildren", 0)

set(objects[10], "Name", "Ult")
set(objects[10], "Size", UDim2.fromOffset(163, 27))
set(objects[10], "Position", UDim2.new(0.5, 0, -0.83999997, 29))
set(objects[10], "AnchorPoint", Vector2.new(0.5, 0))
set(objects[10], "Visible", false)
set(objects[10], "ZIndex", 8)
set(objects[10], "Active", false)
set(objects[10], "ActiveQueryNames", "")
set(objects[10], "Attributes", "")
set(objects[10], "AttributesReplicate", "")
set(objects[10], "AttributesSerialize", "")
set(objects[10], "AutoLocalize", true)
set(objects[10], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[10], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[10], "BorderColor", BrickColor.new("Black"))
set(objects[10], "ClippedRect", Rect.new(-math.huge, -math.huge, math.huge, math.huge))
set(objects[10], "ClipsDescendants", false)
set(objects[10], "Confidential", false)
set(objects[10], "DefinesCapabilities", false)
set(objects[10], "DragBeginConnectionCount", 0)
set(objects[10], "DragStoppedConnectionCount", 0)
set(objects[10], "Draggable", false)
set(objects[10], "FontSize", Enum.FontSize.Size18)
set(objects[10], "GuiState", Enum.GuiState.Idle)
set(objects[10], "InputSink", Enum.InputSink.None)
set(objects[10], "Interactable", true)
set(objects[10], "IsNotOccluded", true)
set(objects[10], "LayoutOrder", 0)
set(objects[10], "LocalizationMatchIdentifier", "")
set(objects[10], "LocalizationMatchedSourceText", "")
set(objects[10], "Localize", true)
set(objects[10], "LocalizedText", "[G]")
set(objects[10], "MouseEnterConnectionCount", 0)
set(objects[10], "MouseLeaveConnectionCount", 0)
set(objects[10], "MouseMovedConnectionCount", 0)
set(objects[10], "MouseWheelBackwardConnectionCount", 0)
set(objects[10], "MouseWheelForwardConnectionCount", 0)
set(objects[10], "OpenTypeFeaturesError", "")
set(objects[10], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[10], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[10], "RawRect2D", Rect.new(508.5, 725.5, 671.5, 752.5))
set(objects[10], "ReplicatedInsertionOrder", 430)
set(objects[10], "Rotation", 0)
set(objects[10], "Sandboxed", false)
set(objects[10], "Selectable", false)
set(objects[10], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[10], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[10], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[10], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[10], "SelectionGroup", false)
set(objects[10], "SelectionOrder", 0)
set(objects[10], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[10], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[10], "SourceAssetId", -1)
set(objects[10], "Tags", "")
set(objects[10], "Text", "[G]")
set(objects[10], "TextColor", BrickColor.new("Institutional white"))
set(objects[10], "TextSize", 18)
set(objects[10], "TextWrap", false)
set(objects[10], "TextXAlignment", Enum.TextXAlignment.Center)
set(objects[10], "TextYAlignment", Enum.TextYAlignment.Center)
set(objects[10], "TotalGroupScale", 1)
set(objects[10], "Transparency", 1)
set(objects[10], "archivable", true)
set(objects[10], "className", "TextLabel")
set(objects[10], "numExpectedDirectChildren", 0)

set(objects[11], "Name", "TextLabel")
set(objects[11], "Size", UDim2.fromOffset(163, 27))
set(objects[11], "Position", UDim2.new(0.5, 2, 0, 2))
set(objects[11], "AnchorPoint", Vector2.new(0.5, 0))
set(objects[11], "Visible", true)
set(objects[11], "ZIndex", 3)
set(objects[11], "Active", false)
set(objects[11], "ActiveQueryNames", "")
set(objects[11], "Attributes", "")
set(objects[11], "AttributesReplicate", "")
set(objects[11], "AttributesSerialize", "")
set(objects[11], "AutoLocalize", true)
set(objects[11], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[11], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[11], "BorderColor", BrickColor.new("Black"))
set(objects[11], "ClippedRect", Rect.new(-math.huge, -math.huge, math.huge, math.huge))
set(objects[11], "ClipsDescendants", false)
set(objects[11], "Confidential", false)
set(objects[11], "DefinesCapabilities", false)
set(objects[11], "DragBeginConnectionCount", 0)
set(objects[11], "DragStoppedConnectionCount", 0)
set(objects[11], "Draggable", false)
set(objects[11], "FontSize", Enum.FontSize.Size18)
set(objects[11], "GuiState", Enum.GuiState.Idle)
set(objects[11], "InputSink", Enum.InputSink.None)
set(objects[11], "Interactable", true)
set(objects[11], "IsNotOccluded", true)
set(objects[11], "LayoutOrder", 0)
set(objects[11], "LocalizationMatchIdentifier", "")
set(objects[11], "LocalizationMatchedSourceText", "")
set(objects[11], "Localize", true)
set(objects[11], "LocalizedText", "[G]")
set(objects[11], "MouseEnterConnectionCount", 0)
set(objects[11], "MouseLeaveConnectionCount", 0)
set(objects[11], "MouseMovedConnectionCount", 0)
set(objects[11], "MouseWheelBackwardConnectionCount", 0)
set(objects[11], "MouseWheelForwardConnectionCount", 0)
set(objects[11], "OpenTypeFeaturesError", "")
set(objects[11], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[11], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[11], "RawRect2D", Rect.new(510.5, 727.5, 673.5, 754.5))
set(objects[11], "ReplicatedInsertionOrder", 428)
set(objects[11], "Rotation", 0)
set(objects[11], "Sandboxed", false)
set(objects[11], "Selectable", false)
set(objects[11], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[11], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[11], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[11], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[11], "SelectionGroup", false)
set(objects[11], "SelectionOrder", 0)
set(objects[11], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[11], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[11], "SourceAssetId", -1)
set(objects[11], "Tags", "")
set(objects[11], "Text", "[G]")
set(objects[11], "TextColor", BrickColor.new("Really black"))
set(objects[11], "TextSize", 18)
set(objects[11], "TextWrap", false)
set(objects[11], "TextXAlignment", Enum.TextXAlignment.Center)
set(objects[11], "TextYAlignment", Enum.TextYAlignment.Center)
set(objects[11], "TotalGroupScale", 1)
set(objects[11], "Transparency", 1)
set(objects[11], "archivable", true)
set(objects[11], "className", "TextLabel")
set(objects[11], "numExpectedDirectChildren", 0)

set(objects[12], "Name", "ImageLabel")
set(objects[12], "Size", UDim2.fromOffset(84, 91))
set(objects[12], "Position", UDim2.fromScale(0.5, -2))
set(objects[12], "AnchorPoint", Vector2.new(0.5, 0.5))
set(objects[12], "Visible", false)
set(objects[12], "ZIndex", 1)
set(objects[12], "Active", false)
set(objects[12], "ActiveQueryNames", "")
set(objects[12], "Attributes", "")
set(objects[12], "AttributesReplicate", "")
set(objects[12], "AttributesSerialize", "")
set(objects[12], "AutoLocalize", true)
set(objects[12], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[12], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[12], "BorderColor", BrickColor.new("Black"))
set(objects[12], "ClippedRect", Rect.new(-math.huge, -math.huge, math.huge, math.huge))
set(objects[12], "ClipsDescendants", false)
set(objects[12], "ContentImageSize", Vector2.new())
set(objects[12], "DefinesCapabilities", false)
set(objects[12], "DragBeginConnectionCount", 0)
set(objects[12], "DragStoppedConnectionCount", 0)
set(objects[12], "Draggable", false)
set(objects[12], "GuiState", Enum.GuiState.Idle)
set(objects[12], "ImageRectOffset", Vector2.new())
set(objects[12], "ImageRectSize", Vector2.new())
set(objects[12], "InputSink", Enum.InputSink.None)
set(objects[12], "Interactable", true)
set(objects[12], "IsNotOccluded", true)
set(objects[12], "LayoutOrder", 0)
set(objects[12], "Localize", true)
set(objects[12], "MouseEnterConnectionCount", 0)
set(objects[12], "MouseLeaveConnectionCount", 0)
set(objects[12], "MouseMovedConnectionCount", 0)
set(objects[12], "MouseWheelBackwardConnectionCount", 0)
set(objects[12], "MouseWheelForwardConnectionCount", 0)
set(objects[12], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[12], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[12], "RawRect2D", Rect.new(548, 626, 632, 717))
set(objects[12], "ReplicatedInsertionOrder", 429)
set(objects[12], "ResampleMode", Enum.ResamplerMode.Default)
set(objects[12], "Rotation", 0)
set(objects[12], "Sandboxed", false)
set(objects[12], "Selectable", false)
set(objects[12], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[12], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[12], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[12], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[12], "SelectionGroup", false)
set(objects[12], "SelectionOrder", 0)
set(objects[12], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[12], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[12], "SourceAssetId", -1)
set(objects[12], "Tags", "")
set(objects[12], "TotalGroupScale", 1)
set(objects[12], "Transparency", 1)
set(objects[12], "archivable", true)
set(objects[12], "className", "ImageLabel")
set(objects[12], "numExpectedDirectChildren", 0)

set(objects[13], "Name", "ImageButton")
set(objects[13], "Size", UDim2.fromScale(1, 1))
set(objects[13], "Position", UDim2.new())
set(objects[13], "AnchorPoint", Vector2.new())
set(objects[13], "Visible", true)
set(objects[13], "ZIndex", 13)
set(objects[13], "Active", true)
set(objects[13], "ActiveQueryNames", "")
set(objects[13], "Attributes", "")
set(objects[13], "AttributesReplicate", "")
set(objects[13], "AttributesSerialize", "")
set(objects[13], "AutoButtonColor", true)
set(objects[13], "AutoLocalize", true)
set(objects[13], "AutomaticSize", Enum.AutomaticSize.None)
set(objects[13], "BackgroundColor", BrickColor.new("Institutional white"))
set(objects[13], "BorderColor", BrickColor.new("Really black"))
set(objects[13], "ClippedRect", Rect.new(-math.huge, -math.huge, math.huge, math.huge))
set(objects[13], "ClipsDescendants", false)
set(objects[13], "ContentImageSize", Vector2.new())
set(objects[13], "DefinesCapabilities", false)
set(objects[13], "DragBeginConnectionCount", 0)
set(objects[13], "DragStoppedConnectionCount", 0)
set(objects[13], "Draggable", false)
set(objects[13], "GuiState", Enum.GuiState.Idle)
set(objects[13], "ImageRectOffset", Vector2.new())
set(objects[13], "ImageRectSize", Vector2.new())
set(objects[13], "InputSink", Enum.InputSink.None)
set(objects[13], "Interactable", true)
set(objects[13], "IsNotOccluded", true)
set(objects[13], "LayoutOrder", 0)
set(objects[13], "Localize", true)
set(objects[13], "Modal", false)
set(objects[13], "MouseButton1ClickConnectionCount", 0)
set(objects[13], "MouseButton1DownConnectionCount", 0)
set(objects[13], "MouseButton1UpConnectionCount", 0)
set(objects[13], "MouseButton2ClickConnectionCount", 0)
set(objects[13], "MouseButton2DownConnectionCount", 0)
set(objects[13], "MouseButton2UpConnectionCount", 0)
set(objects[13], "MouseEnterConnectionCount", 0)
set(objects[13], "MouseLeaveConnectionCount", 0)
set(objects[13], "MouseMovedConnectionCount", 0)
set(objects[13], "MouseWheelBackwardConnectionCount", 0)
set(objects[13], "MouseWheelForwardConnectionCount", 0)
set(objects[13], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[13], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[13], "RawRect2D", Rect.new(391.5, 717.5, 788.5, 742.5))
set(objects[13], "ReplicatedInsertionOrder", 431)
set(objects[13], "ResampleMode", Enum.ResamplerMode.Default)
set(objects[13], "Rotation", 0)
set(objects[13], "Sandboxed", false)
set(objects[13], "Selectable", true)
set(objects[13], "Selected", false)
set(objects[13], "SelectionBehaviorDown", Enum.SelectionBehavior.Escape)
set(objects[13], "SelectionBehaviorLeft", Enum.SelectionBehavior.Escape)
set(objects[13], "SelectionBehaviorRight", Enum.SelectionBehavior.Escape)
set(objects[13], "SelectionBehaviorUp", Enum.SelectionBehavior.Escape)
set(objects[13], "SelectionGroup", false)
set(objects[13], "SelectionOrder", 0)
set(objects[13], "SelectionRect2D", Rect.new(0, 0, 0, 0))
set(objects[13], "SizeConstraint", Enum.SizeConstraint.RelativeXY)
set(objects[13], "SourceAssetId", -1)
set(objects[13], "Style", Enum.ButtonStyle.Custom)
set(objects[13], "Tags", "")
set(objects[13], "TotalGroupScale", 1)
set(objects[13], "Transparency", 1)
set(objects[13], "archivable", true)
set(objects[13], "className", "ImageButton")
set(objects[13], "numExpectedDirectChildren", 0)

set(objects[14], "Name", "UIScale")
set(objects[14], "Attributes", "")
set(objects[14], "AttributesReplicate", "")
set(objects[14], "AttributesSerialize", "")
set(objects[14], "DefinesCapabilities", false)
set(objects[14], "PredictionMode", Enum.PredictionMode.Automatic)
set(objects[14], "PropertyStatusStudio", Enum.PropertyStatus.Ok)
set(objects[14], "Sandboxed", false)
set(objects[14], "Scale", 1)
set(objects[14], "SourceAssetId", -1)
set(objects[14], "Tags", "")
set(objects[14], "archivable", true)
set(objects[14], "className", "UIScale")
set(objects[14], "numExpectedDirectChildren", 0)

-- Parent assignments
setParent(objects[1], game.StarterGui)
setParent(objects[2], objects[1])
setParent(objects[3], objects[2])
setParent(objects[4], objects[3])
setParent(objects[5], objects[4])
setParent(objects[6], objects[5])
setParent(objects[7], objects[3])
setParent(objects[8], objects[2])
setParent(objects[9], objects[8])
setParent(objects[10], objects[2])
setParent(objects[11], objects[10])
setParent(objects[12], objects[10])
setParent(objects[13], objects[2])
setParent(objects[14], objects[1])

-- Late properties
set(objects[13], "HoverImage", "")
set(objects[13], "PressedImage", "")

-- Final visual properties
set(objects[2], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[2], "BackgroundTransparency", 1)
set(objects[2], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[2], "BorderMode", Enum.BorderMode.Outline)
set(objects[2], "BorderSizePixel", 1)
set(objects[3], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[3], "BackgroundTransparency", 1)
set(objects[3], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[3], "BorderMode", Enum.BorderMode.Outline)
set(objects[3], "BorderSizePixel", 1)
set(objects[4], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[4], "BackgroundTransparency", 1)
set(objects[4], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[4], "BorderMode", Enum.BorderMode.Outline)
set(objects[4], "BorderSizePixel", 0)
set(objects[4], "Image", "rbxassetid://7884720727")
set(objects[4], "ImageColor3", Color3.fromRGB(255, 87, 87))
set(objects[4], "ImageTransparency", 1)
set(objects[4], "ScaleType", Enum.ScaleType.Stretch)
set(objects[4], "SliceCenter", Rect.new(0, 0, 0, 0))
set(objects[4], "SliceScale", 1)
set(objects[4], "TileSize", UDim2.fromScale(1, 1))
set(objects[5], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[5], "BackgroundTransparency", 1)
set(objects[5], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[5], "BorderMode", Enum.BorderMode.Outline)
set(objects[5], "BorderSizePixel", 0)
set(objects[5], "Image", "rbxassetid://7884720727")
set(objects[5], "ImageColor3", Color3.fromRGB(255, 87, 87))
set(objects[5], "ImageTransparency", 0)
set(objects[5], "ScaleType", Enum.ScaleType.Stretch)
set(objects[5], "SliceCenter", Rect.new(0, 0, 0, 0))
set(objects[5], "SliceScale", 1)
set(objects[5], "TileSize", UDim2.fromScale(1, 1))
set(objects[6], "Color", ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(200, 200, 200)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 255))
    }))
set(objects[6], "Enabled", true)
set(objects[6], "Offset", Vector2.new())
set(objects[6], "Rotation", -90)
set(objects[6], "Transparency", NumberSequence.new(0))
set(objects[7], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[7], "BackgroundTransparency", 1)
set(objects[7], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[7], "BorderMode", Enum.BorderMode.Outline)
set(objects[7], "BorderSizePixel", 0)
set(objects[7], "Image", "rbxassetid://7885533165")
set(objects[7], "ImageColor3", Color3.fromRGB(0, 0, 0))
set(objects[7], "ImageTransparency", 0.5)
set(objects[7], "ScaleType", Enum.ScaleType.Stretch)
set(objects[7], "SliceCenter", Rect.new(0, 0, 0, 0))
set(objects[7], "SliceScale", 1)
set(objects[7], "TileSize", UDim2.fromScale(1, 1))
set(objects[8], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[8], "BackgroundTransparency", 1)
set(objects[8], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[8], "BorderMode", Enum.BorderMode.Outline)
set(objects[8], "BorderSizePixel", 1)
set(objects[8], "FontFace", Font.new("rbxasset://fonts/families/Balthazar.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic))
set(objects[8], "LineHeight", 1)
set(objects[8], "MaxVisibleGraphemes", -1)
set(objects[8], "OpenTypeFeatures", "")
set(objects[8], "RichText", false)
set(objects[8], "TextColor3", Color3.fromRGB(255, 255, 255))
set(objects[8], "TextDirection", Enum.TextDirection.Auto)
set(objects[8], "TextScaled", false)
set(objects[8], "TextStrokeColor3", Color3.fromRGB(0, 0, 0))
set(objects[8], "TextStrokeTransparency", 0.75)
set(objects[8], "TextTransparency", 0)
set(objects[8], "TextTruncate", Enum.TextTruncate.None)
set(objects[8], "TextWrapped", false)
set(objects[9], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[9], "BackgroundTransparency", 1)
set(objects[9], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[9], "BorderMode", Enum.BorderMode.Outline)
set(objects[9], "BorderSizePixel", 1)
set(objects[9], "FontFace", Font.new("rbxasset://fonts/families/Balthazar.json", Enum.FontWeight.Bold, Enum.FontStyle.Italic))
set(objects[9], "LineHeight", 1)
set(objects[9], "MaxVisibleGraphemes", -1)
set(objects[9], "OpenTypeFeatures", "")
set(objects[9], "RichText", false)
set(objects[9], "TextColor3", Color3.fromRGB(0, 0, 0))
set(objects[9], "TextDirection", Enum.TextDirection.Auto)
set(objects[9], "TextScaled", false)
set(objects[9], "TextStrokeColor3", Color3.fromRGB(0, 0, 0))
set(objects[9], "TextStrokeTransparency", 0.75)
set(objects[9], "TextTransparency", 0)
set(objects[9], "TextTruncate", Enum.TextTruncate.None)
set(objects[9], "TextWrapped", false)
set(objects[10], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[10], "BackgroundTransparency", 1)
set(objects[10], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[10], "BorderMode", Enum.BorderMode.Outline)
set(objects[10], "BorderSizePixel", 1)
set(objects[10], "FontFace", Font.new("rbxasset://fonts/families/Balthazar.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic))
set(objects[10], "LineHeight", 1)
set(objects[10], "MaxVisibleGraphemes", -1)
set(objects[10], "OpenTypeFeatures", "")
set(objects[10], "RichText", false)
set(objects[10], "TextColor3", Color3.fromRGB(255, 255, 255))
set(objects[10], "TextDirection", Enum.TextDirection.Auto)
set(objects[10], "TextScaled", false)
set(objects[10], "TextStrokeColor3", Color3.fromRGB(255, 255, 255))
set(objects[10], "TextStrokeTransparency", 1)
set(objects[10], "TextTransparency", 0)
set(objects[10], "TextTruncate", Enum.TextTruncate.None)
set(objects[10], "TextWrapped", false)
set(objects[11], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[11], "BackgroundTransparency", 1)
set(objects[11], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[11], "BorderMode", Enum.BorderMode.Outline)
set(objects[11], "BorderSizePixel", 1)
set(objects[11], "FontFace", Font.new("rbxasset://fonts/families/Balthazar.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic))
set(objects[11], "LineHeight", 1)
set(objects[11], "MaxVisibleGraphemes", -1)
set(objects[11], "OpenTypeFeatures", "")
set(objects[11], "RichText", false)
set(objects[11], "TextColor3", Color3.fromRGB(0, 0, 0))
set(objects[11], "TextDirection", Enum.TextDirection.Auto)
set(objects[11], "TextScaled", false)
set(objects[11], "TextStrokeColor3", Color3.fromRGB(255, 255, 255))
set(objects[11], "TextStrokeTransparency", 1)
set(objects[11], "TextTransparency", 0)
set(objects[11], "TextTruncate", Enum.TextTruncate.None)
set(objects[11], "TextWrapped", false)
set(objects[12], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[12], "BackgroundTransparency", 1)
set(objects[12], "BorderColor3", Color3.fromRGB(27, 42, 53))
set(objects[12], "BorderMode", Enum.BorderMode.Outline)
set(objects[12], "BorderSizePixel", 1)
set(objects[12], "Image", "rbxassetid://12553547082")
set(objects[12], "ImageColor3", Color3.fromRGB(255, 255, 255))
set(objects[12], "ImageTransparency", 0)
set(objects[12], "ScaleType", Enum.ScaleType.Stretch)
set(objects[12], "SliceCenter", Rect.new(0, 0, 0, 0))
set(objects[12], "SliceScale", 1)
set(objects[12], "TileSize", UDim2.fromScale(1, 1))
set(objects[13], "BackgroundColor3", Color3.fromRGB(255, 255, 255))
set(objects[13], "BackgroundTransparency", 1)
set(objects[13], "BorderColor3", Color3.fromRGB(0, 0, 0))
set(objects[13], "BorderMode", Enum.BorderMode.Outline)
set(objects[13], "BorderSizePixel", 0)
set(objects[13], "Image", "")
set(objects[13], "ImageColor3", Color3.fromRGB(255, 255, 255))
set(objects[13], "ImageTransparency", 1)
set(objects[13], "ScaleType", Enum.ScaleType.Stretch)
set(objects[13], "SliceCenter", Rect.new(0, 0, 0, 0))
set(objects[13], "SliceScale", 1)
set(objects[13], "TileSize", UDim2.fromScale(1, 1))

-- Pastefy integration for scripts and modules
local HttpService = game:GetService("HttpService")
local _MODULES = {}

-- Override require to use Pastefy modules
local _originalRequire = require
_G.require = function(modulePath)
    if _MODULES[modulePath] then return _MODULES[modulePath] end
    return _originalRequire(modulePath)
end

-- Script: LocalScript (LocalScript)
task.spawn(function()
    local success, response = pcall(HttpService.GetAsync, HttpService, "data:text/plain;base64,\\\"task.wait();\\\\nlocal l_Parent_0 = script.Parent;\\\\nlocal l_LocalPlayer_0 = game.Players.LocalPlayer;\\\\nlocal l_Parent_1 = script.Parent.Parent.Parent;\\\\nlocal l_Character_0 = l_LocalPlayer_0.Character;\\\\nlocal _ = l_Character_0.PrimaryPart;\\\\nlocal l_UserInputService_0 = game:GetService(\\\\\\\"UserInputService\\\\\\\");\\\\nlocal v6 = false;\\\\nl_Parent_1.Visible = true;\\\\nlocal v7 = nil;\\\\nlocal function v9() --[[ Line: 12 ]]\\\\n    -- upvalues: l_Parent_1 (copy), l_Character_0 (copy), v6 (ref), v7 (ref), l_UserInputService_0 (copy)\\\\n    local _ = l_Parent_1:FindFirstChild(\\\\\\\"TextLabel\\\\\\\");\\\\n    if l_Character_0:FindFirstChild(\\\\\\\"UFW\\\\\\\") or workspace.CurrentCamera.CameraType == Enum.CameraType.Scriptable or v6 or l_Character_0:FindFirstChild(\\\\\\\"HideUlt\\\\\\\") or l_Character_0:GetAttribute(\\\\\\\"Ulted\\\\\\\") and (l_Character_0:GetAttribute(\\\\\\\"Character\\\\\\\") == \\\\\\\"Bald\\\\\\\" or l_Character_0:GetAttribute(\\\\\\\"Character\\\\\\\") == \\\\\\\"KJ\\\\\\\") then\\\\n        if not v7 then\\\\n            l_Parent_1:TweenPosition(UDim2.new(0.5, 0, 1, 100), Enum.EasingDirection.InOut, Enum.EasingStyle.Quad, 1, true);\\\\n            v7 = true;\\\\n            return;\\\\n        end;\\\\n    elseif v7 then\\\\n        l_Parent_1:TweenPosition(UDim2.new(0.5, 0, 1, -(l_UserInputService_0.TouchEnabled and 150 or 90)), Enum.EasingDirection.InOut, Enum.EasingStyle.Quad, 1, true);\\\\n        v7 = false;\\\\n    end;\\\\nend;\\\\nlocal function _() --[[ Line: 27 ]]\\\\n    -- upvalues: l_UserInputService_0 (copy)\\\\n    local l_Ult_0 = script.Parent.Parent.Parent.Ult;\\\\n    local l_TextLabel_1 = l_Ult_0.TextLabel;\\\\n    if l_UserInputService_0.GamepadEnabled then\\\\n        l_Ult_0.Text = \\\\\\\"[DPAD UP]\\\\\\\";\\\\n        l_TextLabel_1.Text = \\\\\\\"[DPAD UP]\\\\\\\";\\\\n        return;\\\\n    else\\\\n        l_Ult_0.Text = \\\\\\\"[G]\\\\\\\";\\\\n        l_TextLabel_1.Text = \\\\\\\"[G]\\\\\\\";\\\\n        return;\\\\n    end;\\\\nend;\\\\nl_Parent_1.ImageButton.MouseButton1Click:Connect(function() --[[ Line: 40 ]]\\\\n    -- upvalues: l_Character_0 (copy)\\\\n    local v13 = l_Character_0:FindFirstChild(\\\\\\\"Communicate\\\\\\\") or l_Character_0:WaitForChild(\\\\\\\"Communicate\\\\\\\", 5);\\\\n    if v13 then\\\\n        v13:FireServer({\\\\n            Goal = \\\\\\\"KeyPress\\\\\\\", \\\\n            Key = Enum.KeyCode.G, \\\\n            MoveDirection = l_Character_0.Humanoid.MoveDirection\\\\n        });\\\\n    end;\\\\nend);\\\\nscript.Parent.Parent.Parent.Ult:GetPropertyChangedSignal(\\\\\\\"Visible\\\\\\\"):Connect(function() --[[ Line: 51 ]]\\\\n    -- upvalues: l_UserInputService_0 (copy)\\\\n    script.Parent.Parent.Parent.Ult.ImageLabel.Visible = l_UserInputService_0.GamepadEnabled and script.Parent.Parent.Parent.Ult.Visible or false;\\\\nend);\\\\nlocal v14 = nil;\\\\nlocal function v17() --[[ Line: 56 ]]\\\\n    -- upvalues: l_Parent_0 (copy), v14 (ref), l_LocalPlayer_0 (copy), l_UserInputService_0 (copy)\\\\n    l_Parent_0:TweenSize(UDim2.new((v14 or l_LocalPlayer_0:GetAttribute(\\\\\\\"Ultimate\\\\\\\")) / 100, 0, 0, 25), nil, nil, 0.4, true);\\\\n    local l_Ult_1 = script.Parent.Parent.Parent.Ult;\\\\n    local l_TextLabel_2 = l_Ult_1.TextLabel;\\\\n    if l_UserInputService_0.GamepadEnabled then\\\\n        l_Ult_1.Text = \\\\\\\"[DPAD UP]\\\\\\\";\\\\n        l_TextLabel_2.Text = \\\\\\\"[DPAD UP]\\\\\\\";\\\\n    else\\\\n        l_Ult_1.Text = \\\\\\\"[G]\\\\\\\";\\\\n        l_TextLabel_2.Text = \\\\\\\"[G]\\\\\\\";\\\\n    end;\\\\n    if l_LocalPlayer_0:GetAttribute(\\\\\\\"Ultimate\\\\\\\") >= 100 then\\\\n        script.Parent.Parent.Parent.Ult.Visible = true;\\\\n        return;\\\\n    else\\\\n        script.Parent.Parent.Parent.Ult.Visible = false;\\\\n        return;\\\\n    end;\\\\nend;\\\\nlocal _ = l_Character_0:GetAttributeChangedSignal(\\\\\\\"Ulted\\\\\\\"):Connect(function(_) --[[ Line: 67 ]]\\\\n    -- upvalues: l_Character_0 (copy), v6 (ref), v14 (ref), v17 (copy), v9 (copy), l_LocalPlayer_0 (copy)\\\\n    if not l_Character_0:GetAttribute(\\\\\\\"Ulted\\\\\\\") then\\\\n        return;\\\\n    elseif l_Character_0:GetAttribute(\\\\\\\"Character\\\\\\\") == \\\\\\\"Bald\\\\\\\" or l_Character_0:GetAttribute(\\\\\\\"Character\\\\\\\") == \\\\\\\"KJ\\\\\\\" then\\\\n        return;\\\\n    elseif not l_Character_0:GetAttribute(\\\\\\\"UltimateTime\\\\\\\") then\\\\n        return;\\\\n    else\\\\n        local v19 = tick();\\\\n        local v20 = false;\\\\n        v6 = true;\\\\n        v14 = 100;\\\\n        v17();\\\\n        v9();\\\\n        local v21 = nil;\\\\n        v21 = l_LocalPlayer_0.Backpack.ChildAdded:Connect(function(v22) --[[ Line: 84 ]]\\\\n            -- upvalues: v19 (copy), v21 (ref), l_LocalPlayer_0 (ref), v20 (ref)\\\\n            if tick() - v19 > 10 then\\\\n                return v21:Disconnect();\\\\n            elseif v22:IsA(\\\\\\\"Tool\\\\\\\") and game:GetService(\\\\\\\"CollectionService\\\\\\\"):HasTag(v22, \\\\\\\"Ultimate\\\\\\\" .. l_LocalPlayer_0.Name) then\\\\n                v20 = true;\\\\n                return v21:Disconnect();\\\\n            else\\\\n                return;\\\\n            end;\\\\n        end);\\\\n        repeat\\\\n            task.wait();\\\\n        until v20 or tick() - v19 > 10;\\\\n        v6 = nil;\\\\n        v9();\\\\n        if v21 then\\\\n            v21:Disconnect();\\\\n        end;\\\\n        if tick() - v19 > 10 then\\\\n            v14 = nil;\\\\n            return v17();\\\\n        else\\\\n            local l_NumberValue_0 = Instance.new(\\\\\\\"NumberValue\\\\\\\");\\\\n            l_NumberValue_0.Value = 1;\\\\n            l_NumberValue_0:GetPropertyChangedSignal(\\\\\\\"Value\\\\\\\"):Connect(function() --[[ Line: 106 ]]\\\\n                -- upvalues: v14 (ref), l_NumberValue_0 (ref), v17 (ref)\\\\n                v14 = l_NumberValue_0.Value * 100;\\\\n                v17();\\\\n            end);\\\\n            local l_PrimaryPart_1 = l_Character_0.PrimaryPart;\\\\n            local v25 = nil;\\\\n            v25 = l_PrimaryPart_1:GetAttributeChangedSignal(\\\\\\\"fill\\\\\\\"):Connect(function() --[[ Line: 112 ]]\\\\n                -- upvalues: l_PrimaryPart_1 (copy), v14 (ref), l_NumberValue_0 (ref), v25 (ref), v17 (ref)\\\\n                local l_l_PrimaryPart_1_Attribute_0 = l_PrimaryPart_1:GetAttribute(\\\\\\\"fill\\\\\\\");\\\\n                if not l_l_PrimaryPart_1_Attribute_0 or l_l_PrimaryPart_1_Attribute_0 <= 0 then\\\\n                    v14 = nil;\\\\n                    l_NumberValue_0:Destroy();\\\\n                    l_NumberValue_0 = nil;\\\\n                    v25:Disconnect();\\\\n                    return v17();\\\\n                else\\\\n                    l_NumberValue_0.Value = l_l_PrimaryPart_1_Attribute_0;\\\\n                    return;\\\\n                end;\\\\n            end);\\\\n            return;\\\\n        end;\\\\n    end;\\\\nend);\\\\nl_LocalPlayer_0:GetAttributeChangedSignal(\\\\\\\"Ultimate\\\\\\\"):Connect(v17);\\\\nif (l_LocalPlayer_0:GetAttribute(\\\\\\\"Ultimate\\\\\\\") or 0) >= 100 then\\\\n    local l_Ult_2 = script.Parent.Parent.Parent.Ult;\\\\n    local l_TextLabel_3 = l_Ult_2.TextLabel;\\\\n    if l_UserInputService_0.GamepadEnabled then\\\\n        l_Ult_2.Text = \\\\\\\"[DPAD UP]\\\\\\\";\\\\n        l_TextLabel_3.Text = \\\\\\\"[DPAD UP]\\\\\\\";\\\\n    else\\\\n        l_Ult_2.Text = \\\\\\\"[G]\\\\\\\";\\\\n        l_TextLabel_3.Text = \\\\\\\"[G]\\\\\\\";\\\\n    end;\\\\n    script.Parent.Parent.Parent.Ult.Visible = true;\\\\nend;\\\\nworkspace.CurrentCamera:GetPropertyChangedSignal(\\\\\\\"CameraType\\\\\\\"):Connect(v9);\\\\nl_Character_0:GetAttributeChangedSignal(\\\\\\\"Ulted\\\\\\\"):Connect(v9);\\\\nl_Character_0.ChildAdded:Connect(v9);\\\\nl_Character_0.ChildRemoved:Connect(v9);\\\\nl_Parent_0.Size = UDim2.new((l_LocalPlayer_0:GetAttribute(\\\\\\\"Ultimate\\\\\\\") or 0) / 100, 0, 0, 25);\\\"")
    if success then
        local scriptEnv = { script = { Name = "LocalScript", Parent = objects[4], ClassName = "LocalScript" } }
        local chunk, err = loadstring(response)
        if chunk then
            setfenv(chunk, scriptEnv)
            pcall(chunk)
        end
    end
end)

-- Script: LocalScript (LocalScript)
task.spawn(function()
    local success, response = pcall(HttpService.GetAsync, HttpService, "data:text/plain;base64,\\\"task.wait();\\\\nlocal l_Parent_0 = script.Parent;\\\\ngame.Players.LocalPlayer.PlayerGui:WaitForChild(\\\\\\\"ShiftLock\\\\\\\"):WaitForChild(\\\\\\\"SkipButton\\\\\\\").MouseButton1Down:Connect(function() --[[ Line: 6 ]]\\\\n    shared.sfx({\\\\n        SoundId = \\\\\\\"rbxassetid://6895079853\\\\\\\", \\\\n        Parent = workspace, \\\\n        Volume = 0.5\\\\n    }):Play();\\\\n    if game.Players.LocalPlayer.Character:GetAttribute(\\\\\\\"DiedEmote\\\\\\\") then\\\\n        game.Players.LocalPlayer.Character:FindFirstChild(\\\\\\\"Communicate\\\\\\\"):FireServer({\\\\n            Goal = \\\\\\\"SkipEmote\\\\\\\"\\\\n        });\\\\n    end;\\\\nend);\\\\nlocal v1 = l_Parent_0:FindFirstChild(\\\\\\\"TextLabel\\\\\\\") or l_Parent_0:WaitForChild(\\\\\\\"TextLabel\\\\\\\", 1);\\\\nl_Parent_0:GetPropertyChangedSignal(\\\\\\\"Text\\\\\\\"):Connect(function() --[[ Line: 22 ]]\\\\n    -- upvalues: v1 (copy), l_Parent_0 (copy)\\\\n    v1.Text = l_Parent_0.Text;\\\\nend);\\\\nlocal l_LocalPlayer_0 = game.Players.LocalPlayer;\\\\nlocal v3 = l_LocalPlayer_0.Character or l_LocalPlayer_0.CharacterAdded:wait();\\\\nlocal function v5() --[[ Line: 29 ]]\\\\n    -- upvalues: v3 (copy), l_Parent_0 (copy)\\\\n    local l_v3_Attribute_0 = v3:GetAttribute(\\\\\\\"UltimateName\\\\\\\");\\\\n    if v3:GetAttribute(\\\\\\\"IceBoss\\\\\\\") then\\\\n        l_v3_Attribute_0 = \\\\\\\"SUB-ZERO SLASH STORM\\\\\\\";\\\\n    end;\\\\n    l_Parent_0.Text = l_v3_Attribute_0;\\\\n    if l_Parent_0.Text == \\\\\\\"SORCERER\\\\\\\" then\\\\n        script.Parent.Parent.Visible = false;\\\\n    end;\\\\nend;\\\\nv3:GetAttributeChangedSignal(\\\\\\\"UltimateName\\\\\\\"):Connect(v5);\\\\nv3:GetAttributeChangedSignal(\\\\\\\"IceBoss\\\\\\\"):Connect(v5);\\\\nif v3:GetAttribute(\\\\\\\"UltimateName\\\\\\\") then\\\\n    local l_v3_Attribute_1 = v3:GetAttribute(\\\\\\\"UltimateName\\\\\\\");\\\\n    if v3:GetAttribute(\\\\\\\"IceBoss\\\\\\\") then\\\\n        l_v3_Attribute_1 = \\\\\\\"SUB-ZERO SLASH STORM\\\\\\\";\\\\n    end;\\\\n    l_Parent_0.Text = l_v3_Attribute_1;\\\\n    if l_Parent_0.Text == \\\\\\\"SORCERER\\\\\\\" then\\\\n        script.Parent.Parent.Visible = false;\\\\n        return;\\\\n    end;\\\\nelse\\\\n    l_Parent_0.Text = \\\\\\\"SELECT CHARACTER\\\\\\\";\\\\nend;\\\"")
    if success then
        local scriptEnv = { script = { Name = "LocalScript", Parent = objects[8], ClassName = "LocalScript" } }
        local chunk, err = loadstring(response)
        if chunk then
            setfenv(chunk, scriptEnv)
            pcall(chunk)
        end
    end
end)

-- Restore original require (optional)
_G.require = _originalRequire

return objects[1]
