return {
	Name = "Death",
	Animation = "Death/AnimationData.lua",
	Sounds = "Death/Sounds.lua",
	VFX = "Death/VFX.lua",
	Camera = "Death/Camera.lua",
	Cleanup = "Death/Cleanup.lua",
	Assets = "Death/Assets.lua",
	WalkSpeed = 5.333333492279053,
	Looped = true,
	Priority = "Action4",
	Cancels = {
		Jump = true,
		Dash = true,
		SideDash = true,
		BackDash = true,
		Block = true,
		M1 = true,
		OtherEmote = true,
		ToolActivation = false,
		MoveUse = false,
	},
	BlockMoves = true,
}
